/**
 * Type aliases for Supabase table Row/Insert/Update.
 * Source of truth: lib/database.types.ts — autogenerated with
 *   npx supabase gen types typescript --local
 * Do not edit database.types.ts; regenerate after schema changes.
 */

import type { Database } from "@/lib/database.types";

type PublicTables = Database["public"]["Tables"];

export type DbProfile = PublicTables["profiles"]["Row"];
export type DbProfileInsert = PublicTables["profiles"]["Insert"];
export type DbProfileUpdate = PublicTables["profiles"]["Update"];

export type DbInterviewSession = PublicTables["interview_sessions"]["Row"];
export type DbInterviewSessionInsert = PublicTables["interview_sessions"]["Insert"];
export type DbInterviewSessionUpdate = PublicTables["interview_sessions"]["Update"];

export type DbSessionTranscript = PublicTables["session_transcripts"]["Row"];
export type DbSessionTranscriptInsert = PublicTables["session_transcripts"]["Insert"];

export type DbCanvasState = PublicTables["canvas_states"]["Row"];
export type DbCanvasStateInsert = PublicTables["canvas_states"]["Insert"];
export type DbCanvasStateUpdate = PublicTables["canvas_states"]["Update"];

export type DbSessionSettings = PublicTables["session_settings"]["Row"];
export type DbSessionSettingsInsert = PublicTables["session_settings"]["Insert"];
export type DbSessionSettingsUpdate = PublicTables["session_settings"]["Update"];

export type DbStripeCustomer = PublicTables["stripe_customers"]["Row"];
export type DbStripeCustomerInsert = PublicTables["stripe_customers"]["Insert"];

export type DbTokenPurchase = PublicTables["token_purchases"]["Row"];
export type DbTokenPurchaseInsert = PublicTables["token_purchases"]["Insert"];

export type DbUserPreference = PublicTables["user_preferences"]["Row"];
export type DbUserPreferenceInsert = PublicTables["user_preferences"]["Insert"];
export type DbUserPreferenceUpdate = PublicTables["user_preferences"]["Update"];
